#!/usr/bin/env python3
"""IMO-style forward-scatter report: pings.csv -> hourly echo counts, emailed.

Citizen-science submission: builds an IMO-inspired hourly echo-count report
for a UTC day from the GRAVES ping log and emails it to the configured IMO
address via SMTP (Gmail app password from config.ini [email] - the same
account Uhura's comm station uses, [redacted]).

This is a "forward-scatter echo counts" report in the spirit of the IMO's
radio-meteor campaigns. The exact recipient/format guidance changes over
time - check https://www.imo.net/observations/ and set [imo] to accordingly.
By default this script only builds the report; pass --send to email it.

Usage:
  python3 imo_report.py --config config.ini --date 2026-08-03
  python3 imo_report.py --config config.ini --send
  python3 imo_report.py --config config.ini --pull-from-vostro --send
"""

import argparse
import configparser
import csv
import datetime
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
VOSTRO = "station-host"
VOSTRO_REPO = "~/Starfall-Sentinel"


def build_parser():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--config", default=os.path.join(HERE, "config.ini"))
    p.add_argument("--pings", default=None, help="path to pings.csv")
    p.add_argument("--pull-from-vostro", action="store_true",
                   help="fetch pings.csv from the station host via SSH first")
    p.add_argument("--date", default=None,
                   help="UTC date to report (default: yesterday)")
    p.add_argument("--send", action="store_true",
                   help="actually email the report (default: build only)")
    p.add_argument("--out", default=None, help="write the report text here")
    return p


def load_ini(config_path):
    cfg = {}
    if os.path.exists(config_path):
        cp = configparser.ConfigParser()
        cp.read(config_path)
        for section in ("detector", "station", "email", "imo"):
            if cp.has_section(section):
                cfg[section] = dict(cp[section])
    return cfg


def fetch_pings_from_vostro():
    cmd = ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=8", VOSTRO,
           f"cat {VOSTRO_REPO}/data/pings.csv"]
    return subprocess.run(cmd, capture_output=True, check=True).stdout


def build_report(pings_text, date_str, station, observer, station_name):
    counts = {h: 0 for h in range(24)}
    long_events = 0
    for line in pings_text.splitlines():
        row = next(csv.reader([line]))
        if len(row) < 8 or not row[0].startswith("20"):
            continue
        if not row[0].startswith(date_str):
            continue
        if row[7] == "LONG":
            long_events += 1
            continue  # sporadic-E, not a meteor echo
        try:
            hour = int(row[0][11:13])
            counts[hour] += 1
        except ValueError:
            continue
    total = sum(counts.values())
    lines = [
        "IMO-STYLE FORWARD-SCATTER ECHO COUNT REPORT",
        f"Date (UTC): {date_str}",
        f"Station: {station_name}",
        f"Observer: {observer}",
        f"Lat/Lon: {station.get('lat', '?')}, {station.get('lon', '?')}",
        f"Target: GRAVES radar 143.050 MHz (forward scatter, horizontal)",
        f"Total PING echoes: {total}   (LONG/sporadic-E events excluded: {long_events})",
        "",
        "Hour(UTC)  Echoes",
    ]
    for h in range(24):
        lines.append(f"{h:02d}:00      {counts[h]}")
    lines.append("")
    lines.append("Generated by Starfall Sentinel (https://github.com/ciberjohn/Starfall-Sentinel)")
    return "\n".join(lines)


def send_email(cfg, subject, body):
    import smtplib
    from email.mime.text import MIMEText
    email_cfg = cfg.get("email", {})
    imo_cfg = cfg.get("imo", {})
    user = email_cfg.get("user", "")
    password = email_cfg.get("password", "")
    to = imo_cfg.get("to", "")
    if not user or not password or not to:
        raise RuntimeError(
            "[email] user/password or [imo] to missing in config.ini - "
            "build-only mode; set them to enable --send")
    host = email_cfg.get("smtp_host", "smtp.gmail.com")
    port = int(email_cfg.get("smtp_port", "587"))
    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = to
    with smtplib.SMTP(host, port, timeout=30) as s:
        s.starttls()
        s.login(user, password)
        s.send_message(msg)
    return to


def main():
    args = build_parser().parse_args()
    cfg = load_ini(args.config)

    if args.pull_from_vostro:
        print(f"[imo-report] pulling pings.csv from {VOSTRO} ...", flush=True)
        pings_text = fetch_pings_from_vostro().decode(errors="replace")
    else:
        pings_path = args.pings or cfg.get("detector", {}).get("log", "data/pings.csv")
        with open(pings_path) as f:
            pings_text = f.read()

    date_str = args.date or (
        datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=1)
    ).strftime("%Y-%m-%d")

    station = cfg.get("station", {})
    imo_cfg = cfg.get("imo", {})
    report = build_report(
        pings_text, date_str, station,
        observer=imo_cfg.get("observer", "anonymous"),
        station_name=imo_cfg.get("station_name", "Starfall Sentinel"))

    if args.out:
        with open(args.out, "w") as f:
            f.write(report + "\n")
        print(f"[imo-report] wrote {args.out}", flush=True)
    else:
        print(report, flush=True)

    if args.send:
        to = send_email(cfg,
                        f"Starfall Sentinel forward-scatter report {date_str}",
                        report)
        print(f"[imo-report] emailed to {to}", flush=True)


if __name__ == "__main__":
    main()
